### ISSUE TITLE
Colour of h2 in light mode

### ISSUE THREAD

**Issue by panda9903** [Flow-Launcher/flow-launcher.github.io#38]
Hello... I observed that two sections, Customisations and Sponsor look good in dark mode, but when switching to light mode, they are not visible, due to the  colour being the same as  the background colour.
![image](https://github.com/Flow-Launcher/flow-launcher.github.io/assets/97980368/7ad0ec28-6820-46ba-9b13-ca4acaf4e503)
![image](https://github.com/Flow-Launcher/flow-launcher.github.io/assets/97980368/2c010704-81c1-42df-a0c7-45ec7649ffb0)

And also, the button for toggling back to dark mode is not the same as the dark mode one. I don't know if that is intentional or it was by mistake. 
![image](https://github.com/Flow-Launcher/flow-launcher.github.io/assets/97980368/bb1051b3-64ec-4aa6-98aa-a89c8fdfc5b8)

Please assign me this issue, as this is  good first issue, and I am a beginner.
Thanks :)

**Comment by JohnTheGr8** [comment]
paging the captain @onesounds

**Comment by panda9903** [comment]
Hi.. Can you please assign me this issue? I can start working on it right away.

**Comment by jjw24** [comment]
Hey how's it going. Thank you for taking an interest in helping out with our website, really appreciated.

Before you start, let's confirm a couple of things:
1. The light mode toggle button does seem different, but I would like to confirm with onesound first.

2. Customizations heading seems correct to me viewing in Edge browser:
![image](https://github.com/Flow-Launcher/flow-launcher.github.io/assets/26427004/b198b967-78b6-4b51-8a0a-e0f6b6b4fcd8)
How to repro your issue?

3. Sponsors section looks ok to me, could you expand on where the issue is please.
![image](https://github.com/Flow-Launcher/flow-launcher.github.io/assets/26427004/9cc0a424-5aba-46db-814a-ba4094a1e2de)

**Comment by onesounds** [comment]
1. h2 header not visible issue
mine is fine.

2. toggle icon
my intended is - moon icon when light(white) page, and sun icon when dark(black) page.

There was no problem with the browser I tested. If you think it needs to be fixed, please pr. (You have to write down in detail about problem so that I can test it.) I'll check and reflect it properly.

**Comment by panda9903** [comment]
Thanks for replying so quick, Everything is looking good now. The background colors for the sections are changed. And also the dark mode icon too.
I wanted to tell you that I use flow launcher and it is wonderful. It makes life so much easier.
Please text me if there are any good issues I can work on, as I am a beginner. I am very interested to help you.
Thanks 
Good day :)
